fix: Fixed a bug where double ? would be generated for stubs
Safe-DS/Stub-Generator pull request #103
Opened 2024-04-07 12:43 UTC by Masara

Closes #87

### Summary of Changes

Fixed the bug described in #87.

2024-04-08 15:46 UTC, lars-reimann requested changes
This does not fully fix the issue. `Literal["Test"] | None` gets translated to `literal<"Test">?` for example. The `?` syntax for nullability is only supported for named Safe-DS types (class types/enum types/enum variant types/type parameter types). Out of those, you probably only generate class types.

For this literal type you could create `literal<"Test", null>` instead. For everything else, you need the `union` with `Nothing?`.

2024-04-10 13:48 UTC, lars-reimann requested changes

2024-04-10 13:48 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/TestStubFileGeneration.test_stub_creation[type_var_module].sdsstub
> +    data: union<Map<String, Any>, Nothing?> = null
This was fine before.

2024-04-10 13:48 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/TestStubFileGeneration.test_stub_creation[type_var_module].sdsstub
> +    data: union<Map<String, List<T>>, Nothing?>
This was fine before.

2024-04-10 13:48 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/TestStubFileGeneration.test_stub_creation[function_module].sdsstub
> +    @PythonName("literal_none") literalNone: union<Nothing?, literal<"1", 2>>,
```suggestion
    @PythonName("literal_none") literalNone: literal<"1", 2, null>,
```

2024-04-10 13:48 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/TestStubFileGeneration.test_stub_creation[function_module].sdsstub
> +    @PythonName("tuple_class_none") tupleClassNone: union<Nothing?, Tuple<Int, String>>
Would it be possible to consistently add `Nothing?` at the end of the union?

2024-04-10 13:48 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/TestStubFileGeneration.test_stub_creation[function_module].sdsstub
> +    @PythonName("list_class_none") listClassNone: union<List<Float>, Nothing?>,
```suggestion
    @PythonName("list_class_none") listClassNone: List<Float>?,
```

2024-04-10 13:48 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/TestStubFileGeneration.test_stub_creation[function_module].sdsstub
> +    @PythonName("set_none") setNone: union<Nothing?, Set<Int>>,
```suggestion
    @PythonName("set_none") setNone: Set<Int>?,
```

2024-04-10 13:48 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/TestStubFileGeneration.test_stub_creation[function_module].sdsstub
> +    @PythonName("dict_none") dictNone: union<Map<String, Int>, Nothing?>,
```suggestion
    @PythonName("dict_none") dictNone: Map<String, Int>?,
```

2024-04-10 13:48 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/TestStubFileGeneration.test_stub_creation[function_module].sdsstub
> +    @PythonName("none_list_union_none_none") noneListUnionNoneNone: union<List<Nothing?>, Nothing?>,
This was fine before.

2024-04-10 19:34 UTC, Masara commented
I hope everything is all right now

2024-04-11 20:07 UTC, lars-reimann commented
Looks good now, I'll review it tomorrow evening if the conflicts are resolved.

2024-04-13 09:21 UTC, lars-reimann approved these changes
👍

2024-04-13 09:21 UTC, merged

2024-05-04 15:37 UTC, lars-reimann commented
:tada: This PR is included in version 0.3.0 :tada:

The release is available on:
- `v0.3.0`
- [GitHub release](https://github.com/Safe-DS/Stub-Generator/releases/tag/v0.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: