feat: Correct stubs for TypeVars
Safe-DS/Stub-Generator pull request #67
Opened 2024-02-25 15:51 UTC by Masara

Closes #63

### Summary of Changes
TypeVars create correct stubs.

2024-02-25 15:53 UTC, Masara commented
@lars-reimann Like I once mentioned [here](https://github.com/Safe-DS/Stub-Generator/issues/36#issuecomment-1819603549) Mypy seems to be unable to parse square brackets right after function and class names. Therefor I had to use a workaround to get the TypeVar information we need for ```def fun[T](a: T) -> T``` like functions. The parameter type and return type are seen as "special Any types" in Mypy and I used that information to assume that we've got a TypeVar. You can see the changes concerning this "workaround" here: 9c30988bbba5a7232ef9f32be4f5f219ddacfbc0

2024-02-25 15:54 UTC, Masara commented
Also it seems like Python 3.11 can't work with the tests containing the ```def my_fun[T]``` syntax, what should I do in this case?

2024-02-25 16:46 UTC, lars-reimann commented
> Also it seems like Python 3.11 can't work with the tests containing the `def my_fun[T]` syntax, what should I do in this case?

That syntax was introduced in Python 3.12, so that's not surprising. Until `mypy` supports [PEP 695](https://peps.python.org/pep-0695/) natively, I'm fine with adding a new issue for that syntax to the backlog. Supporting this is not an urgent feature.

2024-02-25 17:58 UTC, Masara commented
I removed the changes and created issue #68. You can now check the PR.

2024-02-25 19:56 UTC, lars-reimann requested changes
Nice work, this requires only minor changes.

2024-02-25 19:56 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/test_type_var_creation.sdsstub
> +fun typeVarFunc<_type_var>(
Type parameter names should be `UpperCamelCase`. `@PythonName` is not needed for them, but the names must be replaced consistently.

2024-02-25 19:56 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/test_type_var_creation.sdsstub
> +fun multipleTypeVar<_type_var1, _type_var2>(
Same.

2024-02-25 19:56 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/test_type_var_creation.sdsstub
A test for a class with type parameters is missing.

2024-02-26 00:11 UTC, Masara commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/test_type_var_creation.sdsstub
Am I right to assume that this
```py
T = TypeVar('T')

class TypeVarClass:
    def __init__(self, items: list[T]): ...

    def type_var_class_func(self, a: T) -> T: ...
```

would look like this in the stubs
```py
class TypeVarClass<T>(
	items: List<T>
) {
	@Pure
	@PythonName("type_var_class_func")
	fun typeVarClassFunc(
		a: T
	) -> result1: T
}
```
?

2024-02-26 08:39 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/test_type_var_creation.sdsstub
Yes, although additionally the class must inherit from something like `Generic` (see [this](https://mypy.readthedocs.io/en/stable/generics.html#defining-generic-classes)).

2024-02-26 09:44 UTC, Masara commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/test_type_var_creation.sdsstub
So it should look like this?
```py
from typing import TypeVar, Generic
T = TypeVar('T')

class TypeVarClass(Generic[T]):
    def __init__(self): ...

    def type_var_class_func(self, a: T) -> T: ...
```
to
```
class TypeVarClass<T>(
	items: List<T>
) {
	@Pure
	@PythonName("type_var_class_func")
	fun typeVarClassFunc(
		a: T
	) -> result1: T
}
```

2024-02-26 09:45 UTC, Masara commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/test_type_var_creation.sdsstub
So it should look like this?
```py
from typing import TypeVar, Generic
T = TypeVar('T')

class TypeVarClass(Generic[T]):
    def __init__(self): ...

    def type_var_class_func(self, a: T) -> T: ...
```
to
```
class TypeVarClass<T>() {
	@Pure
	@PythonName("type_var_class_func")
	fun typeVarClassFunc(
		a: T
	) -> result1: T
}
```

2024-02-26 10:19 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/__snapshots__/test_generate_stubs/test_type_var_creation.sdsstub
I'd suggest combining both of your examples, i.e. keeping the constructor parameter:

```py
from typing import TypeVar, Generic
T = TypeVar('T')

class TypeVarClass(Generic[T]):
    def __init__(self, items: list[T]): ...

    def type_var_class_func(self, a: T) -> T: ...
```

to 

```
class TypeVarClass<T>(items: List<T>) {
    @Pure
    @PythonName("type_var_class_func")
    fun typeVarClassFunc(
        a: T
    ) -> result1: T
}
```

2024-02-28 14:47 UTC, Masara commented
@lars-reimann I added the changes you requested. It would be nice, if you also look through the new tests at ```type_var_module.py``` and maybe suggest some more cases, since I don't know how the stubs would look like and what would be legal and what not.

2024-02-29 15:33 UTC, Masara commented
@lars-reimann I'm done here, you can check this PR now, too.

2024-02-29 16:22 UTC, merged

2024-03-29 13:16 UTC, lars-reimann commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on:
- `v0.2.0`
- [GitHub release](https://github.com/Safe-DS/Stub-Generator/releases/tag/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: