feat: Stubs are created for referenced declarations in other packages
Safe-DS/Stub-Generator pull request #70
Opened 2024-02-29 13:58 UTC by Masara

Closes #66

### Summary of Changes

Now limited stubs are created for imported classes from other packages.

2024-03-02 09:01 UTC, lars-reimann requested changes

2024-03-02 19:53 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/test_generate_stubs.py
> +    # Somehow the stubs get overwritten by other tests, therefore we have to call the function before asserting
This does not necessarily have to be done in this PR, though.

2024-03-02 20:30 UTC, Masara commented
@lars-reimann I changed the stubs-generator the way you said and refactored the tests, are the tests like this all right or should I still try to get the file names with ```glob``` like you mentioned [here](https://github.com/Safe-DS/Stub-Generator/pull/69#discussion_r1509919395)?

2024-03-02 20:31 UTC, Masara commented
Also, you can merge this PR first.

2024-03-02 20:54 UTC, lars-reimann commented on tests/safeds_stubgen/stubs_generator/test_generate_stubs.py
> +    for stub_data in stubs_data:
Are you using all entries of `stubs_data`?

2024-03-02 21:32 UTC, Masara commented
@lars-reimann I changed the tests, now all stubs files should be checked

2024-03-02 21:44 UTC, lars-reimann commented
Yep, looks great this way and should be easier to extend later on.

2024-03-02 21:47 UTC, lars-reimann commented on src/safeds_stubgen/stubs_generator/_generate_stubs.py
> +            camel_case_name = _convert_snake_to_camel_case(name)
What happened to this one?

2024-03-02 22:13 UTC, Masara commented on src/safeds_stubgen/stubs_generator/_generate_stubs.py
> +            camel_case_name = _convert_snake_to_camel_case(name)
I renamed the ```_convert_snake_to_camel_case``` function and added the changed you proposed

2024-03-02 22:14 UTC, Masara commented on src/safeds_stubgen/stubs_generator/_generate_stubs.py
> +            camel_case_name = _convert_snake_to_camel_case(name)
Oh nevermind, I misunderstood what you meant, I will add the changes in a moment

2024-03-02 22:17 UTC, lars-reimann commented on src/safeds_stubgen/stubs_generator/_generate_stubs.py
> +            camel_case_name = _convert_snake_to_camel_case(name)
It was mostly about moving the if inside the function, so it's always paired with the call.

2024-03-02 22:32 UTC, Masara commented on src/safeds_stubgen/stubs_generator/_generate_stubs.py
> +            camel_case_name = _convert_snake_to_camel_case(name)
Yes, I fixed that now and removed the if statements

2024-03-03 09:29 UTC, lars-reimann approved these changes
Nice work!

2024-03-03 09:29 UTC, merged

2024-03-29 13:16 UTC, lars-reimann commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on:
- `v0.2.0`
- [GitHub release](https://github.com/Safe-DS/Stub-Generator/releases/tag/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: